nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.8.3.cjs

npmScopes:
  scatter-ly:
    npmRegistryServer: 'https://npm.pkg.github.com'

npmRegistries:
  'https://npm.pkg.github.com':
    npmAlwaysAuth: true
